[package]
name = "minigrep_trial_manikya"
version = "0.1.0"
edition = "2021"
description = "A small scale grep for local files from The Book"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
